# File: js-nvrl/docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sveltekit-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web-network

  nginx:
    image: nginx:latest
    container_name: nginx-js-nvrl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/app/static
    depends_on:
      - app
    networks:
      - web-network

networks:
  web-network:
    driver: bridge