version: '3.8'

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sveltekit_app
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-certs:/etc/letsencrypt
      - ./www/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sveltekit
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
      - ./www/html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --plivicegod@gmail.com --agree-tos --no-eff-email -d js.nvrl.my.id
    depends_on:
      - nginx

volumes:
  certbot-certs:

networks:
  app-network:
    driver: bridge